services:
  - type: web
    name: options-analysis
    env: docker
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      # ---- MODE: LIVE or TEST (SANDBOX) ----
      - key: MODE
        value: TEST

      # ---- Dhan credentials (set one pair depending on MODE) ----
      - key: DHAN_LIVE_CLIENT_ID
        sync: false
      - key: DHAN_LIVE_ACCESS_TOKEN
        sync: false
      - key: DHAN_SANDBOX_CLIENT_ID
        sync: false
      - key: DHAN_SANDBOX_ACCESS_TOKEN
        sync: false

      # ---- Optional: OpenAI (only needed if you use /ai endpoints) ----
      - key: OPENAI_API_KEY
        sync: false

      # CORS (already wide-open in code; keep for clarity)
      - key: ALLOW_ORIGINS
        value: "*"
